version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: daily
    allow:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    commit-message:
      prefix: "ci"
    labels:
      - ci
      - github-actions

  - package-ecosystem: gomod
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: daily
    groups:
      aws-sdk-go-v2:
        patterns:
          - "github.com/aws/aws-sdk-go-v2*"
          - "github.com/aws/smithy-go"
    allow:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    commit-message:
      prefix: "deps"
    labels:
      - dependencies
      - go

  - package-ecosystem: docker
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: daily
    allow:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    commit-message:
      prefix: "container"
    labels:
      - dependencies
      - docker
